@echo off
cd /d "C:\Users\dell\Desktop\NEW APP\airbnb clone\airbnb-clone-react-native"
echo Killing any running Metro processes...
taskkill /F /IM node.exe 2>nul
echo Waiting for clean shutdown...
timeout /t 3 /nobreak >nul
echo Clearing cache and starting Expo...
npx expo start --clear
